name: Deploy Hugo Site

on:
  push:
    branches:
      - master # Change this to your default branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # Install Node.js (if you use npm packages)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Build the Hugo site
    - name: Build Site
      run: hugo --minify

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
